version: "3.8"

services:
  books-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bookstore
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - books-net
    volumes:
      - book-db-vol:/var/lib/mysql
      - ./database/booksstore.sql:/docker-entrypoint-initdb.d/booksstore.sql

  app:
    build: .
    image: books:latest
    restart: always
    environment:
      DB_HOST: books-db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_USER_PASSWORD}
      DB_NAME: bookstore
      PORT: 3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      books-db:
        condition: service_healthy
    networks:
      - books-net

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - books-net

volumes:
  book-db-vol:

networks:
  books-net:
    driver: bridge
